language: python
python:
  - 3.6
  - 3.7.9
  - 3.8
  - 3.9

env:
  global:
      - PYTHONPATH=.

install:
  - "pip install coverage"
  - "pip install coveralls"
  - "pip install -r tests/requirements.txt"
  - "pip install -r requirements.txt"

script:
  - "coverage run -m unittest discover tests"

after_success:
  - coveralls
